name: deeprlbootcamp
channels:
    - menpo
    - soumith
dependencies:
    - python==3.5.3
    - opencv3=3.1.0
    - numpy==1.13.1
    - scipy==0.19.1
    - pip:
        - gym==0.9.2
        - chainer==2.0.1
        - ipdb==0.10.3
        - tblib==1.3.2
        - atari_py==0.1.1
        - Pillow==4.2.1
        - PyOpenGL==3.1.0
        - cloudpickle==0.3.1
        - click==6.7
        - python-dateutil==2.6.1
        - pyyaml==3.12
        - easydict==1.7
        - boto3==1.4.4
        - mako==1.0.7
        - redis==2.10.5
        - Flask==0.12.2
        - plotly==2.0.12
        - tqdm==4.14.0
        - cupy==1.0.1; 'linux' in sys_platform
        - cached-property==1.3.0
        - h5py==2.7.0
